Repository Puakii/DiamondHands, pull requests merged in 2022-06, with the labels that each got.

#38 fixed minor styling + already fixed bug for mobile version
  src/components/CryptoCurrencies/Banner.css
  src/components/CryptoCurrencies/CryptoNavbar.css
  src/components/CryptoCurrencies/CryptoNavbar.js
  src/components/Navbar.css
  src/components/Navbar.js
  src/index.css
  yarn.lock
Labels: bug, enhancement

#41 added pagination for cryptocurrency page and fixed search bug
  src/components/CryptoCurrencies/CoinsTable.css
  src/components/CryptoCurrencies/CoinsTable.js
Labels: bug, enhancement

#42 added currency change feature to home page
  src/components/CryptoAPI.css
  src/components/CryptoAPI.js
  src/components/CryptoCurrencies/CoinsTable.js
  src/config/api.js
Labels: enhancement

#44 added user session to context
  src/App.js
  src/components/Account.js
  src/components/CryptoAPI.js
  src/components/Navbar.css
  src/components/Navbar.js
  src/components/SignIn.js
  src/pages/AccountPage.js
  src/pages/CryptoContext.js
  src/pages/SignInPage.js
Labels: enhancement

#49 Navbar and Account
  package.json
  src/App.js
  src/components/Account.js
  src/components/AccountAvatar.js
  src/components/CryptoCurrencies/CoinsTable.css
  src/components/CryptoCurrencies/CoinsTable.js
  src/components/Navbar.css
  src/components/Navbar.js
  src/pages/AccountPage.js
  src/pages/CryptoContext.js
  src/pages/CryptoPage.js
  yarn.lock
Labels: bug, enhancement

#50 fixed search bar bug and pagination bar and fixed hover styling issue…
  src/components/Account.js
  src/components/CryptoCurrencies/CoinsTable.js
  src/components/Navbar.js
  src/components/SignIn.css
  src/components/SignIn.js
  src/components/SignUp.css
  src/components/SignUp.js
  src/components/Watchlist.js
  src/pages/CryptoContext.js
Labels: bug, enhancement

#53 Added news component and styling for various screen sizes
  src/App.js
  src/components/News.css
  src/components/News.js
  src/config/api.js
  src/pages/CryptoContext.js
  src/pages/NewsPage.js
Labels: enhancement

#54 added live prices update with refreshing feature
  src/components/CryptoAPI.js
  src/components/CryptoCurrencies/Carousel.js
  src/components/CryptoCurrencies/CoinsTable.js
  src/components/Markets/CoinSummary.js
  src/components/Markets/Graph.js
  src/components/Navbar.js
  src/components/News.css
  src/components/News.js
  src/components/Watchlist.js
  src/pages/MultiMarketPage.js
Labels: enhancement

#58 fixed reading from null bug when non signed in user access cryptocurrency page
  src/App.js
  src/components/CryptoCurrencies/CoinsTable.js
  src/components/Navbar.js
  src/components/Watchlist.js
  src/pages/ForumPage.js
Labels: bug

#60 organised file system and updates imports and minor styling changes on home page
  src/components/AccountPage/Account.js
  src/components/AccountPage/AccountAvatar.js
  src/components/CryptoCurrencies/CryptoNavbar.js
  src/components/CryptoCurrenciesPage/Banner.css
  src/components/CryptoCurrenciesPage/Banner.js
  src/components/CryptoCurrenciesPage/Carousel.css
  src/components/CryptoCurrenciesPage/Carousel.js
  src/components/CryptoCurrenciesPage/CoinsTable.css
  src/components/CryptoCurrenciesPage/CoinsTable.js
  src/components/EntireWebsite/Footer.css
  src/components/EntireWebsite/Footer.js
  src/components/EntireWebsite/Navbar.css
  src/components/EntireWebsite/Navbar.js
  src/components/HomePage/CryptoAPI.css
  src/components/HomePage/CryptoAPI.js
  src/components/HomePage/Highlight.css
  src/components/HomePage/Highlight.js
  src/components/MultiMarketPage/CoinSummary.js
  src/components/MultiMarketPage/Graph.js
  src/components/MultiMarketPage/MultiMarketTable.js
  src/components/NewsPage/News.js
  src/components/SignInPage/SignIn.css
  src/components/SignInPage/SignIn.js
  src/components/SignUpPage/SignUp.css
  src/components/SignUpPage/SignUp.js
  src/components/WatchListPage/Watchlist.js
  src/pages/AccountPage.js
  src/pages/CryptoPage.js
  src/pages/HomePage.js
  src/pages/MultiMarketPage.js
  src/pages/NewsPage.js
  src/pages/SignInPage.js
  src/pages/SignUpPage.js
  src/pages/WatchlistPage.js
Labels: enhancement

#61 styling changes for home page
  src/components/Navbar.css
  src/components/News.js
  src/index.css
Labels: enhancement

#62 Added several small enhancement features
  src/components/CryptoCurrenciesPage/CoinsTable.js
  src/components/HomePage/CryptoAPI.css
  src/components/HomePage/CryptoAPI.js
  src/components/HomePage/Highlight.css
  src/components/SignUpPage/SignUp.js
  src/components/WatchListPage/Watchlist.js
Labels: enhancement

#66 Milestone2enhancement
  public/favicon.ico
  public/index.html
  public/manifest.json
  src/components/CryptoCurrenciesPage/CoinsTable.js
  src/components/EntireWebsite/Navbar.js
  src/components/HomePage/CryptoAPI.js
  src/components/MultiMarketPage/CoinSummary.js
  src/components/SignInPage/SignIn.js
  src/components/SignUpPage/SignUp.js
  src/components/WatchListPage/Watchlist.js
  src/pages/CryptoContext.js
  src/pages/MultiMarketPage.js
Labels: bug, enhancement

#69 fixed name less than 3 characters bug and avatar rendering bug
  src/components/AccountPage/AccountAvatar.js
  src/components/HomePage/CryptoAPI.js
  src/components/SignUpPage/SignUp.js
  src/pages/CryptoContext.js
Labels: bug

#71 Fix magic link users not having a row in profile table
  src/components/EntireWebsite/Navbar.js
  src/components/SignInPage/SignIn.js
  src/components/WatchListPage/Watchlist.js
  src/pages/CryptoContext.js
Labels: bug

#73 fixed styling issue on home page for 14inch screen and hide private k…
  src/components/EntireWebsite/Navbar.css
  src/components/HomePage/CryptoAPI.css
  src/components/HomePage/Highlight.css
  src/config/api.js
Labels: bug, documentation, enhancement

#74 Username glitch fix
  src/components/WatchListPage/Watchlist.js
Labels: bug

#75 fix username glitch v2
  src/components/WatchListPage/Watchlist.js
Labels: bug

#76 final username glitch fix
  src/components/WatchListPage/Watchlist.js
  src/pages/CryptoContext.js
Labels: bug
