Repository Puakii/DiamondHands, pull requests merged in 2022-07, with the labels that each got.

#78 Reset password feature
  package.json
  src/App.js
  src/components/AccountPage/Account.js
  src/components/CryptoCurrenciesPage/Carousel.js
  src/components/CryptoCurrenciesPage/CoinsTable.js
  src/components/EntireWebsite/Navbar.js
  src/components/HomePage/CryptoAPI.js
  src/components/HomePage/Highlight.js
  src/components/MultiMarketPage/CoinSummary.js
  src/components/MultiMarketPage/Graph.js
  src/components/MultiMarketPage/MultiMarketTable.js
  src/components/ResetPasswordPage/ResetPassword.css
  src/components/ResetPasswordPage/ResetPassword.js
  src/components/SignInPage/SignIn.css
  src/components/SignInPage/SignIn.js
  src/components/SignUpPage/SignUp.js
  src/components/UpdatePasswordPage/UpdatePassword.css
  src/components/UpdatePasswordPage/UpdatePassword.js
  src/components/WatchListPage/Watchlist.js
  src/index.js
  src/pages/CryptoContext.js
  src/pages/MultiMarketPage.js
  src/pages/ResetPasswordPage.js
  src/pages/UpdatePasswordPage.js
  yarn.lock
Labels: bug, enhancement

#79 saved currency change to local storage
  src/pages/CryptoContext.js
Labels: enhancement

#80 added price alert and link to supabase
  src/App.js
  src/components/AccountPage/Account.js
  src/components/CryptoCurrenciesPage/Carousel.js
  src/components/CryptoCurrenciesPage/CoinsTable.js
  src/components/EntireWebsite/Footer.js
  src/components/EntireWebsite/Navbar.js
  src/components/HomePage/CryptoAPI.js
  src/components/HomePage/Highlight.js
  src/components/MultiMarketPage/CoinSummary.js
  src/components/MultiMarketPage/Graph.js
  src/components/MultiMarketPage/MultiMarketTable.js
  src/components/ResetPasswordPage/ResetPassword.js
  src/components/SignInPage/SignIn.js
  src/components/SignUpPage/SignUp.js
  src/components/UpdatePasswordPage/UpdatePassword.js
  src/components/WatchListPage/Watchlist.js
  src/context/CryptoContext.js
  src/context/PriceAlertContext.js
  src/index.js
  src/pages/MultiMarketPage.js
Labels: bug, enhancement

#81 Added price alert in navigation bar
  src/components/EntireWebsite/Navbar.js
  src/components/MultiMarketPage/CoinSummary.js
  src/context/PriceAlertContext.js
Labels: enhancement

#83 added individual post page and replies
  src/App.js
  src/components/EntireWebsite/Navbar.js
  src/components/ForumPage/AddReply.js
  src/components/ForumPage/IndividualPost.js
  src/components/ForumPage/Posts.js
  src/components/ForumPage/Replies.js
  src/components/MultiMarketPage/CoinSummary.js
  src/context/PriceAlertContext.js
  src/pages/IndivForumPage.js
  src/pages/MultiMarketPage.js
Labels: enhancement

#84 Price alert and forum
  src/components/ForumPage/AddPost.js
  src/components/ForumPage/Posts.js
  src/components/MultiMarketPage/CoinSummary.js
  src/components/NewsPage/News.js
  src/components/WatchListPage/Watchlist.js
Labels: bug, enhancement

#87 Forum
  src/components/EntireWebsite/Navbar.js
  src/components/MultiMarketPage/Alert.js
  src/context/PriceAlertContext.js
Labels: bug, enhancement

#86 fix alert issue and implment mobile responsiveness
  src/components/EntireWebsite/Navbar.js
  src/components/ForumPage/AddReply.js
  src/components/ForumPage/IndividualPost.js
  src/components/ForumPage/Posts.js
  src/components/ForumPage/Replies.js
Labels: bug, enhancement

#88 Fixed the bug where removing alerts doesnt get reflected correctly in…
  src/components/EntireWebsite/Navbar.js
  src/context/PriceAlertContext.js
Labels: bug, enhancement

#89 Forum.v3
  src/components/EntireWebsite/Navbar.js
  src/components/ForumPage/AddPost.js
  src/components/ForumPage/IndividualPost.js
  src/components/ForumPage/Posts.js
  src/components/MultiMarketPage/Alert.js
  src/context/PriceAlertContext.js
Labels: bug, enhancement

#90 added news search feature and styling for individual post
  src/components/ForumPage/IndividualPost.js
  src/components/ForumPage/Replies.js
  src/components/NewsPage/News.js
Labels: enhancement

#91 added username to posts and replies
  src/components/ForumPage/AddPost.js
  src/components/ForumPage/AddReply.js
  src/components/ForumPage/IndividualPost.js
  src/components/ForumPage/Posts.js
  src/components/ForumPage/Replies.js
Labels: enhancement

#100 Forum.v4
  src/components/EntireWebsite/Navbar.js
  src/components/ForumPage/AddPost.js
  src/components/ForumPage/AddReply.js
  src/components/ForumPage/IndividualPost.js
  src/components/ForumPage/Posts.js
  src/components/ForumPage/Replies.js
  src/components/MultiMarketPage/Alert.js
  src/context/CryptoContext.js
  src/context/PriceAlertContext.js
Labels: bug, enhancement

#102 added wider search capability as well as delete for navigation bar alerts
  src/components/AccountPage/Account.js
  src/components/EntireWebsite/Navbar.js
  src/components/ForumPage/IndividualPost.js
  src/components/NewsPage/News.js
  src/components/WatchListPage/Watchlist.js
Labels: enhancement

#105 fix bug for live alerts and add button bug fix
  src/components/EntireWebsite/Navbar.css
  src/components/EntireWebsite/Navbar.js
  src/components/ForumPage/AddPost.js
  src/components/ForumPage/AddReply.js
  src/components/ForumPage/IndividualPost.js
  src/components/ForumPage/Replies.js
  src/components/MultiMarketPage/Alert.js
  src/components/SignInPage/SignIn.js
  src/components/SignUpPage/SignUp.js
  src/components/WatchListPage/Watchlist.js
  src/context/CryptoContext.js
  src/context/PriceAlertContext.js
Labels: bug

#108 fix lag
  src/context/PriceAlertContext.js
Labels: bug

#109 Forum.v5
  src/components/ForumPage/Posts.js
  src/components/ForumPage/Replies.js
  src/components/MultiMarketPage/Alert.js
  src/components/NewsPage/News.js
Labels: enhancement

#110 change redirection of reset password
  src/components/ResetPasswordPage/ResetPassword.js
Labels: bug

#113 added testcases
  package.json
  src/__tests__/Footer.test.js
  src/__tests__/News.test.js
  src/__tests__/__snapshots__/News.test.js.snap
  src/components/EntireWebsite/Footer.js
  yarn.lock
Labels: documentation

#114 Update README.md
  README.md
Labels: documentation
